### ISSUE TITLE
Maven is not able to resolve the dependency for this project

### ISSUE THREAD

**Issue by aimanjaffer** [PitneyBowes/pitneybowes-shipping-api-java#1]
On adding this dependency to the pom.xml file I face this error:
**Missing artifact org.pitneybowes:shippingapi:jar:1.0.0**
On performing a maven clean and install I face these errors:
**[WARNING] The POM for org.pitneybowes:shippingapi:jar:1.0.0 is missing, no dependency information available**
**[ERROR] Failed to execute goal on project xxx: Could not resolve dependencies for project com.xxx.xxxx: Failure to find org.pitneybowes:shippingapi:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]**

Will greatly appreciate any help in resolving this issue. Thank you.

**Comment by ghost** [comment]
Hi Aiman,

We are in process of hosting our SDK to maven repository that is why you are getting error.

Steps mentioned in ReadMe page is to install SDK locally and use it in your project, 

For now you can download project and follow instructions to install SDK locally and then include it in your project. 


Regards
Amit

**Comment by psyklopz** [comment]
Seem that this is still an issue?

**Comment by ghost** [comment]
Hi Iqra,

Could you please look into this issue.

Regards
Amit
